data <- subset(read.table("household_power_consumption.txt", header=T, sep=";", na.strings=c('?')), Date=="1/2/2007" | Date=="2/2/2007")
png(file="plot2.png")
plot(data$Global_active_power, type="l", axes=F, xlab="", ylab="Global Active Power (kilowatts)")
axis(1, at=c(1, nrow(data)/2, nrow(data)),labels=c("Thu","Fri","Sat"))
axis(2)
box()
dev.off()